# Numpy   (2022.01.06)

* numpy 모듈 선언
* 홈페이지 : https://numpy.org/

In [6]:
import numpy as np

In [13]:
np.__version__

'1.20.3'

## 1. Array 정의 및 사용
* 시퀀스 데이터 ( 리스트, 튜플 등 ) 로부터 배열 생성
* https://numpy.org/doc/stable/reference/arrays.html

In [6]:
data1 = [1,2,3]
data1

[1, 2, 3]

In [7]:
data2 = [1,2,3,3.5,5]
data2

[1, 2, 3, 3.5, 5]

### 1-1. 리스트 객체를 이용하여 array생성

In [8]:
arr1 = np.array(data1)
arr1

array([1, 2, 3])

#### array 크기 확인

In [10]:
arr1.shape

(3,)

#### 리스트를 직접 입력하여 array 생성

In [11]:
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [12]:
arr2.shape

(5,)

#### array의 자료형 확인

In [14]:
arr2.dtype     # c언어 기반이기 때문에 데이터 형식이 세분화되어있어서 int32가 뜸

dtype('int32')

In [15]:
arr3 = np.array([1,2,3,3.5,4])       # 실수가 더 큰 범위이므로 실수가 하나라도 
arr3                                 # 들어가면 소수점 처리해버림

array([1. , 2. , 3. , 3.5, 4. ])

In [16]:
arr3.dtype     # dtype = data type

dtype('float64')

In [17]:
arr3.shape

(5,)

In [22]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr4.shape

(3, 3)

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(1,5)

array([1, 2, 3, 4])

In [27]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [28]:
np.arange(12).reshape(3,4)      # reshape(행,열)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
b1 = np.arange(12).reshape(3,4)
b1.shape

(3, 4)

## 2. 범위를 지정해 배열생성2 : linspace()함수
> 형식 : arr.obj = np.linspace(start, stop,[num=50])

In [30]:
# 1부터 10사이에 10개의 숫자를 넣는것
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
np.linspace(0,np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [33]:
np.linspace(1,10).shape

(50,)

### 2-1. 특별한 형태의 배열생성
> np.zeros(), np.ones(), np.eye()

* 모든 요소가 0인 배열 생성 : np.zeros(shape, dtype=float)

In [34]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

* 모든 요소가 1인 배열 생성 : np.ones(shape, dtype=none)

In [35]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

* 대각요소가 1인 배열 생성 1 ; np.eye(n,m,k=K,dtype=none)

In [37]:
# 3행 3열의 대각요소가 1인 행렬. 타입이 '' 이면 기본값은 float
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
# 3행 4열의 대각요소가 1인 행렬 생성. 
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [39]:
# k는 열의 인덱스 위치를 의미함.
np.eye(3,4,k=1,dtype=int)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [40]:
np.eye(3,4,k=2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

* 대각요소가 1인 배열 생성 2 : np.identity(n,dtype=none)

In [41]:
# n*n 크기의 단위행렬 생성
np.identity(5)  # 5행 5열

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

* 초기화되지 않은 배열 생성 : np.empty(shape, dtype=float)

In [42]:
np.empty(4)

array([6.44448339e+247, 9.08367203e+223, 2.31647114e-152, 2.64685961e+180])

* 배열의 데이터 타입 변환

    * 문자열 배열을 숫자형 배열로 변환

In [44]:
np.array(['1.5','0.62','2','3.14','3.141592'])

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [46]:
# 문자열인 str_a1을 float형식으로 바꾸는 것
str_a1 = np.array(['1.5','0.62','2','3.14','3.141592'])
num_a1 = str_a1.astype(float)
num_a1

array([1.5     , 0.62    , 2.      , 3.14    , 3.141592])

In [47]:
str_a1.dtype

dtype('<U8')

In [48]:
num_a1.dtype

dtype('float64')

In [52]:
num_a2 = str_a1.astype(float).astype('float32')
num_a2

array([1.5     , 0.62    , 2.      , 3.14    , 3.141592], dtype=float32)

In [54]:
str_a2 = np.array(['1','3','5','7','9'])
num_a2 = str_a2.astype(int)
num_a2

array([1, 3, 5, 7, 9])

* 실수형 배열을 정수형 배열로 변환

In [16]:
num_f1 = np.array([10, 21, 0.549, 4.75, 5.98])
num_f1

array([10.   , 21.   ,  0.549,  4.75 ,  5.98 ])

In [56]:
num_i1 = num_f1.astype(int)
num_i1

array([10, 21,  0,  4,  5])

In [57]:
num_f1.dtype

dtype('float64')

In [60]:
num_i1.dtype

dtype('int32')

* 숫자형 배열을 문자열 배열로 변환

In [17]:
# 반올림하기
np.around(num_f1)

array([10., 21.,  1.,  5.,  6.])

In [62]:
num_f1.astype('U')

array(['10.0', '21.0', '0.549', '4.75', '5.98'], dtype='<U32')

In [64]:
num_f1.astype('S')

array([b'10.0', b'21.0', b'0.549', b'4.75', b'5.98'], dtype='|S32')

## 3. 난수 배열 생성

### random.rand(), random.randint()

#### random.rand(d0,d1,...,dn)
* 0과1사이의 실수난수를 갖는 numpy배열 생성

In [65]:
np.random.rand()

0.04320281129230619

In [20]:
np.random.rand(3,3,4)

array([[[0.65755866, 0.15300237, 0.53043597, 0.12584811],
        [0.54012753, 0.51569213, 0.1514582 , 0.92918854],
        [0.09437641, 0.77587796, 0.09828656, 0.3586348 ]],

       [[0.2817147 , 0.42996793, 0.37273942, 0.3849081 ],
        [0.09935783, 0.79466575, 0.90434421, 0.6238419 ],
        [0.79659191, 0.38823539, 0.7843929 , 0.11214486]],

       [[0.69158787, 0.12614538, 0.13309486, 0.40452338],
        [0.6391867 , 0.50532374, 0.59220646, 0.2596032 ],
        [0.53009733, 0.55589761, 0.30172354, 0.02727078]]])

#### random.randint(low,high,size)
* [low,high]사이의 정수 난수를 갖는 numpy배열을 생성

In [68]:
np.random.randint(10)

1

In [69]:
np.random.randint(10,20)

18

In [72]:
np.random.randint(10,20,(3,5))

array([[12, 19, 18, 13, 17],
       [14, 10, 14, 11, 18],
       [17, 15, 11, 19, 10]])

## 4. 기본 연산(합, 차, 곱, 나눗셈 등)
: 기본적으로 동일한 크기의 array간 연산 수행

In [7]:
arr1 = np.array([[1,3,4],[4,3,6]])
arr1

array([[1, 3, 4],
       [4, 3, 6]])

In [77]:
arr2 = np.arange(10,16).reshape(2,3)
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [78]:
print(arr1.shape, arr2.shape)

(2, 3) (2, 3)


### 4-1. 배열의 합

In [80]:
arr1 + arr2

array([[11, 14, 16],
       [17, 17, 21]])

### 4-2. 배열의 차

In [81]:
arr1 - arr2

array([[ -9,  -8,  -8],
       [ -9, -11,  -9]])

### 4-3. 배열의 곱

In [82]:
arr1 * arr2

array([[10, 33, 48],
       [52, 42, 90]])

### 4-4. 배열의 나눗셈

In [83]:
arr1 / arr2

array([[0.1       , 0.27272727, 0.33333333],
       [0.30769231, 0.21428571, 0.4       ]])

### 4-5. 배열의 비교 연산

In [84]:
arr2 > 10

array([[False,  True,  True],
       [ True,  True,  True]])

## 5. 배열의 Broadcasting
* 서로 크기가 다른 array들의 연산이 가능하도록 배열을 자동적으로 변환하여 연산 수행

In [8]:
arr1

array([[1, 3, 4],
       [4, 3, 6]])

In [88]:
arr3 = np.array([10,11,12])
arr3

array([10, 11, 12])

In [89]:
(arr1.shape, arr3.shape)

((2, 3), (3,))

In [90]:
arr1 + arr3

array([[11, 14, 16],
       [14, 14, 18]])

In [10]:
arr1 **2

array([[ 1,  9, 16],
       [16,  9, 36]], dtype=int32)

## 6. 통계를 위한 연산   ( 2022.01.07)
* 배열의 합, 평균, 표준편차, 분산, 최소값, 최대값, 누적합, 누적곱 등

In [12]:
arr1 = np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [17]:
# 합과 (산술)평균 :  sum(), mean()
[arr1.sum(), arr1.mean()]

[10, 2.0]

In [18]:
# 표준 편차와 분산 : std(), var()
[arr1.std(), arr1.var()]

[1.4142135623730951, 2.0]

In [21]:
# 최소값과 최대값 : min(), max()
arr1.min(), arr1.max()

(0, 4)

In [22]:
# 누적합과 누적곱 : cumsum(), cumprod()
arr2 = np.arange(1,5)
arr2

array([1, 2, 3, 4])

In [24]:
# 누적합
arr2.cumsum()

array([ 1,  3,  6, 10], dtype=int32)

In [25]:
# 누적곱
arr2.cumprod()

array([ 1,  2,  6, 24], dtype=int32)

## 7. 행렬 연산
* 선형 대수를 위한 행렬연산
* 행렬 곱, 전치 행렬, 역행렬, 행렬식 등
    * 행렬곱(matrix product) : a.dot(B) or np.dot(A,B)
    * 전치행렬 : A.transpose() or np.transpose(A)
    * 역행렬 : np.linalg.inv(A)
    * 행렬식 : np.linalg.det(A)

In [26]:
A = np.arange(1,5).reshape(2,2)
# A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [28]:
B = np.array([3,2,0,1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

### 7-1. 행렬의 곱

In [31]:
A.dot(B)

array([[ 3,  4],
       [ 9, 10]])

In [32]:
np.dot(A,B)

array([[ 3,  4],
       [ 9, 10]])

### 7-2. 전치행렬

In [40]:
A.transpose()     # 차원을 바꾸는 것. ex. 2행3열을 3행2열로 바꾸는 것

array([[1, 3],
       [2, 4]])

In [35]:
np.transpose(B)

array([[3, 0],
       [2, 1]])

### 7-3. 역행렬

In [36]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### 7-4. 행렬식

In [37]:
np.linalg.det(A)

-2.0000000000000004

In [39]:
np.dot(A, np.linalg.inv(A))

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

## 8. Array 인덱싱과 슬라이싱
* 인덱싱 : 배열의 위치나 조건을 지정해 배열의 원소를 선택하는 것
* 슬라이싱 : 범위를 지정해 배열의 원소를 선택하는 것

### 8-1. 1차원 배열의 인덱싱
#### 배열명[위치]
* 파이썬의 인덱싱과 동일
* 0번째로 시작함

In [41]:
arr1[0]

0

In [42]:
arr1[3]

3

In [43]:
# shape : (m, )=>1차원, (m,n)=>2차원, (m,n,p)=>3차원
# 인덱스 [] : [m] => 1차원, [m,n]=>2차원, [mn,n,p]=>3차원
# arr1([1,3,4]) => 3차원 배열의 위치, 1면 3행 4열
# 여러 인덱스의 요소들을 지정할 때는 리스트로 주어야 한다.
arr1[[1,3,4]]

array([1, 3, 4])

In [44]:
arr2 = np.arange(1,13).reshape(3,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
# 2차원의 array에서 인덱싱을 하기 위해선 2개의 인자를 입력해야 한다.
arr2[2,3]    # 인덱스는 0부터 시작하기 때문에 인덱스값을 3을 주면 오류가 나옴

12

In [47]:
# 값 변경
arr2[0,0] = 90
arr2

array([[90,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### 8-1-2. 2차원 배열명[행위치]
: 2차원 배열에서 지정한 행 전체가 선택됨

In [48]:
# 두번째 행 (1행) 선택
arr2[1]

array([5, 6, 7, 8])

#### 8-1-3 2차원 배열명[:, 열위치]
:2차원 배열에서 지정한 열 전체 선택

In [51]:
# 1열 선택
arr2[:,1]

array([ 2,  6, 10])

#### 8-1-4. 2차원 배열의 특정 행을 지정해서 행 전체를 변경

In [53]:
# 두번째 행 변경
arr2[1] = np.array([-5, 1, 10, 9])

In [54]:
# 변경된 배열 확인
arr2

array([[90,  2,  3,  4],
       [-5,  1, 10,  9],
       [ 9, 10, 11, 12]])

#### 8-1-5. 배열명
: 지정한 인덱스의 원소를 가져옴

In [67]:
arr2[[0,2],[0,2]]

array([90, 11])

#### 8-1-6. 배열명[조건]
: 배열에서 조건을 만족하는 원소만 선택

In [56]:
# 10이상인 원소 선택
arr2 > 10

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True]])

In [57]:
arr2[arr2>10]

array([90, 11, 12])

In [59]:
arr2[arr2%2==0]

array([90,  2,  4, 10, 10, 12])

### 8-2. 1차원 배열의 슬라이싱
* 배열[시작위치:끝위치] : 시작위치에서 끝위치-1에 해당하는 배열의 원소를 반환

In [60]:
arr1

array([0, 1, 2, 3, 4])

In [61]:
arr1[1:3]

array([1, 2])

In [62]:
arr1[1:5:2]

array([1, 3])

In [66]:
arr1[:5:2]   # 처음 인덱스 값이 비어있는 경우

array([0, 2, 4])

In [68]:
arr1[1::2]   # 중간에 인덱스 값이 비어있는 경우

array([1, 3])

In [69]:
arr1[::2]    # 처음, 중간 값이 비어있는 경우

array([0, 2, 4])

In [70]:
arr1[::-1]   # 끝 값부터 가져오는 경우

array([4, 3, 2, 1, 0])

In [72]:
arr1[::-2]   # 끝 값부터 2차이로 가져오는 경우

array([4, 2, 0])

### 8-3. 2차원 배열의 슬라이싱

In [73]:
arr2

array([[90,  2,  3,  4],
       [-5,  1, 10,  9],
       [ 9, 10, 11, 12]])

In [74]:
# 인덱스값 2의 모든 요소 꺼내기
arr2[2]

array([ 9, 10, 11, 12])

In [76]:
# 3열의 모든 요소 꺼내기
arr2[:,3]

array([ 4,  9, 12])

In [78]:
# 인덱스 범위가 교차하는 값 산출
arr2[1:3,1:3]

array([[ 1, 10],
       [10, 11]])

In [82]:
arr3 = np.arange(10,100,10).reshape(3,3)
arr3

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [84]:
# 1행의 0열과 1열 요소 선택
arr3[1,:2]
arr3[1][:2]

array([40, 50])

In [86]:
arr3[:2,1:3]=np.array([[1,3],[4,1]])
arr3

array([[10,  1,  3],
       [40,  4,  1],
       [70, 80, 90]])

In [85]:
arr3[2][1]

80

## 9. Array boolean 인덱싱 (Mask)
* 다차원의 인덱싱을 응용하여 boolean 인덱싱
* boolean 인덱싱을 통해 만들어낸 array를 통해 원하는 행 또는 열 값만 뽑아냄
* 가리고 싶은 부분은 가리고, 원하는 요소만 꺼냄

In [87]:
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo',
                  'Park','Beomwoo'])
names

array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park',
       'Beomwoo'], dtype='<U7')

In [88]:
names.shape

(8,)

In [89]:
# 8행 4열의 실수 난수 배열 생성
data = np.random.randn(8,4)
data

array([[-0.62466037,  0.26174321, -0.28761517,  1.41579874],
       [-0.6680825 ,  0.78301641, -0.07915627, -0.22042899],
       [ 0.53928883,  0.03082658,  0.70469791, -0.06932154],
       [-0.3468292 , -0.91641437,  1.44543026,  0.92032372],
       [ 1.25716357, -0.25116615, -0.37348871, -0.57321228],
       [ 2.06147554,  1.32861291,  0.05478093, -0.81569653],
       [ 1.01571947, -0.55669504,  0.03063272, -0.77734374],
       [-1.65665259,  0.48649632, -1.82105813,  0.85631752]])

In [90]:
data.shape

(8, 4)

In [92]:
# 요소가 Beomwoo인 항목에 대한 mask 생성
names_mask_Beomwoo = (names == 'Beomwoo')
names_mask_Beomwoo

array([ True,  True, False, False, False,  True, False,  True])

In [95]:
data[names_mask_Beomwoo]

array([[-0.62466037,  0.26174321, -0.28761517,  1.41579874],
       [-0.6680825 ,  0.78301641, -0.07915627, -0.22042899],
       [ 2.06147554,  1.32861291,  0.05478093, -0.81569653],
       [-1.65665259,  0.48649632, -1.82105813,  0.85631752]])

In [97]:
# 요소가 Kim인 행의 데이터만 꺼내기
names_mask_Kim = (names == 'Kim')
names_mask_Kim
data[names_mask_Kim]

array([[ 0.53928883,  0.03082658,  0.70469791, -0.06932154]])

In [98]:
# 논리 연산을 응용하여, 요소가 Kim 또는 Park인 행의 데이터만 꺼내기
(names == 'Kim')|(names =='Park')

array([False, False,  True, False, False, False,  True, False])

### 9-1. 마스크 인덱싱 문제
* 문제1. 0번째 열이 0보다 작은 행데이터를 추출하기

In [101]:
data[:,0]<0

array([ True,  True, False,  True, False, False, False,  True])

In [103]:
data[data[:,0]<0][2:4]

array([[-0.3468292 , -0.91641437,  1.44543026,  0.92032372],
       [-1.65665259,  0.48649632, -1.82105813,  0.85631752]])

## 10. 수학 관련 함수
* 제곱근, 절대값, 삼각함수, 지수로그함수, 반올림함수 등

In [104]:
# 각 성분의 절대값 계산하기
np.abs(data)

array([[0.62466037, 0.26174321, 0.28761517, 1.41579874],
       [0.6680825 , 0.78301641, 0.07915627, 0.22042899],
       [0.53928883, 0.03082658, 0.70469791, 0.06932154],
       [0.3468292 , 0.91641437, 1.44543026, 0.92032372],
       [1.25716357, 0.25116615, 0.37348871, 0.57321228],
       [2.06147554, 1.32861291, 0.05478093, 0.81569653],
       [1.01571947, 0.55669504, 0.03063272, 0.77734374],
       [1.65665259, 0.48649632, 1.82105813, 0.85631752]])

In [106]:
# 각 성분의 제곱근 계산하기
np.sqrt(np.abs(data))

array([[0.79035459, 0.51160845, 0.53629765, 1.18987341],
       [0.81736314, 0.88488215, 0.28134725, 0.46949866],
       [0.73436287, 0.175575  , 0.83946287, 0.26328983],
       [0.58892206, 0.95729534, 1.20226048, 0.95933504],
       [1.12123306, 0.50116479, 0.61113723, 0.75710784],
       [1.43578395, 1.15265472, 0.23405327, 0.9031592 ],
       [1.00782909, 0.74611999, 0.17502207, 0.88167099],
       [1.28711017, 0.69749288, 1.34946587, 0.92537426]])

### 10-1. 지수함수

In [107]:
# 각 성분을 자연대수 e의 지수로 삼은 값을 계산하기
np.exp(data)

array([[0.53544325, 1.29919288, 0.75005018, 4.11977578],
       [0.51269072, 2.18806242, 0.92389553, 0.8021746 ],
       [1.71478692, 1.03130664, 2.0232354 , 0.93302663],
       [0.70692606, 0.39995055, 4.24367761, 2.51010283],
       [3.51543606, 0.77789312, 0.68832875, 0.56371173],
       [7.85755541, 3.77580239, 1.05630919, 0.44233112],
       [2.76134938, 0.57310001, 1.03110673, 0.45962528],
       [0.19077652, 1.62660711, 0.1618544 , 2.35447441]])

### 10-2. 로그함수
* 자연로그 : log()
* 상용로그 : log10()
* 밑이 2인 로그 : log2()

In [109]:
# 자연로그
np.log(abs(data))

array([[-0.47054718, -1.34039137, -1.2461319 ,  0.34769385],
       [-0.40334361, -0.24460162, -2.53633123, -1.51217969],
       [-0.61750399, -3.47937791, -0.34998606, -2.66899965],
       [-1.05892284, -0.08728664,  0.36840703, -0.0830298 ],
       [ 0.22885805, -1.38164063, -0.98486749, -0.55649916],
       [ 0.72342201,  0.28413548, -2.90441308, -0.20371289],
       [ 0.0155972 , -0.58573769, -3.4856864 , -0.25187263],
       [ 0.50479906, -0.72052594,  0.59941772, -0.15511403]])

In [110]:
# 상용로그
np.log10(abs(data))

array([[-0.20435605, -0.58212457, -0.54118821,  0.15100152],
       [-0.1751699 , -0.10622914, -1.10151466, -0.65673129],
       [-0.26817857, -1.51107463, -0.15199702, -1.15913182],
       [-0.45988435, -0.03790811,  0.15999714, -0.03605938],
       [ 0.09939179, -0.6000389 , -0.42772252, -0.24168451],
       [ 0.31417819,  0.12339847, -1.26137057, -0.08847138],
       [ 0.00677378, -0.25438265, -1.51381437, -0.10938689],
       [ 0.21923144, -0.31292044,  0.26032381, -0.06736517]])

In [111]:
# 밑이 2인 로그
np.log2(abs(data))

array([[-0.67885609, -1.93377598, -1.79778831,  0.5016162 ],
       [-0.58190182, -0.35288555, -3.65915249, -2.18161414],
       [-0.89086994, -5.01968125, -0.50492316, -3.85055255],
       [-1.52770274, -0.12592801,  0.531499  , -0.11978668],
       [ 0.33017238, -1.99328608, -1.42086344, -0.80285858],
       [ 1.04367734,  0.40992084, -4.19018234, -0.29389557],
       [ 0.022502  , -0.84504086, -5.02878249, -0.3633754 ],
       [ 0.72827109, -1.0394992 ,  0.86477697, -0.22378225]])

### 10-3. 기타 수학 함수

In [112]:
# 각 성분의 부호 계산 : sign()
np.sign(data)

array([[-1.,  1., -1.,  1.],
       [-1.,  1., -1., -1.],
       [ 1.,  1.,  1., -1.],
       [-1., -1.,  1.,  1.],
       [ 1., -1., -1., -1.],
       [ 1.,  1.,  1., -1.],
       [ 1., -1.,  1., -1.],
       [-1.,  1., -1.,  1.]])

In [113]:
# 전체 성분의 합을 계산
np.sum(data)

3.154503067360295

In [114]:
# 같은 열을 갖는 행의 요소들을 합한 결과 ( axis = 0 )
np.sum(data, axis=0)

array([ 1.57742275,  1.16641988, -0.32577646,  0.7364369 ])

In [115]:
# 같은 행을 갖는 열의 요소들을 합한 결과 ( axis = 1 )
np.sum(data, axis=1)

array([ 0.76526641, -0.18465135,  1.20549179,  1.1025104 ,  0.05929643,
        2.62917286, -0.28768659, -2.13489688])

In [116]:
# 전체 성분의 평균 계산
np.mean(data)

0.09857822085500922

In [117]:
# 전체 성분의 표준편차 계산
np.std(data)

0.8981088929844412

In [118]:
# 전체 성분의 최소값, 최대값이 위치한 인덱스를 반환
np.argmax(data)

20

In [121]:
# 최대값, 최소값의 위치 인덱스 : argmax(), argmin()
[np.argmax(data), np.argmax(min)]

[20, 0]

In [122]:
# 행방향으로 최대값이 위치한 인덱스 반환
np.argmax(data, axis=1)

array([3, 1, 2, 2, 0, 0, 0, 3], dtype=int64)

In [123]:
# 누적합
np.cumsum(data)

array([-0.62466037, -0.36291716, -0.65053233,  0.76526641,  0.0971839 ,
        0.88020032,  0.80104404,  0.58061505,  1.11990389,  1.15073047,
        1.85542838,  1.78610684,  1.43927764,  0.52286327,  1.96829352,
        2.88861725,  4.14578082,  3.89461467,  3.52112596,  2.94791368,
        5.00938922,  6.33800214,  6.39278307,  5.57708653,  6.592806  ,
        6.03611096,  6.06674368,  5.28939994,  3.63274735,  4.11924367,
        2.29818554,  3.15450307])

In [124]:
# 누적곱
np.cumprod(data)

array([-6.24660371e-01, -1.63500611e-01,  4.70252566e-02,  6.65782989e-02,
       -4.44797965e-02, -3.48284106e-02,  2.75688720e-03, -6.07697853e-04,
       -3.27724664e-04, -1.01026313e-05, -7.11930315e-06,  4.93521035e-07,
       -1.71167505e-07,  1.56860362e-07,  2.26730713e-07,  2.08665654e-07,
        2.62326859e-07, -6.58876259e-08,  2.46082847e-08, -1.41057710e-08,
       -2.90787019e-08, -3.86343389e-08, -2.11642515e-09,  1.72636066e-09,
        1.75349813e-09, -9.76163712e-10, -2.99025544e-11,  2.32445635e-11,
       -3.85081664e-11, -1.87340812e-11,  3.41158508e-11,  2.92140009e-11])

In [125]:
# 전체 성분에 대해서 행 기준 오름차순으로 정렬
np.sort(data)

array([[-0.62466037, -0.28761517,  0.26174321,  1.41579874],
       [-0.6680825 , -0.22042899, -0.07915627,  0.78301641],
       [-0.06932154,  0.03082658,  0.53928883,  0.70469791],
       [-0.91641437, -0.3468292 ,  0.92032372,  1.44543026],
       [-0.57321228, -0.37348871, -0.25116615,  1.25716357],
       [-0.81569653,  0.05478093,  1.32861291,  2.06147554],
       [-0.77734374, -0.55669504,  0.03063272,  1.01571947],
       [-1.82105813, -1.65665259,  0.48649632,  0.85631752]])

In [126]:
# np.sort(data)를 데칼코마니 한 것
np.sort(data)[::-1]

array([[-1.82105813, -1.65665259,  0.48649632,  0.85631752],
       [-0.77734374, -0.55669504,  0.03063272,  1.01571947],
       [-0.81569653,  0.05478093,  1.32861291,  2.06147554],
       [-0.57321228, -0.37348871, -0.25116615,  1.25716357],
       [-0.91641437, -0.3468292 ,  0.92032372,  1.44543026],
       [-0.06932154,  0.03082658,  0.53928883,  0.70469791],
       [-0.6680825 , -0.22042899, -0.07915627,  0.78301641],
       [-0.62466037, -0.28761517,  0.26174321,  1.41579874]])

## 11. 두 개의 array에 적용되는 함수

* add(), subtract(), multiply(), divide()

In [129]:
data1 = np.random.randn(5,3)
data2 = np.random.randn(5,3)

In [130]:
print(data1)
print(data2)

[[ 3.44099149e-04  3.10473254e-01  3.86332598e-01]
 [-2.24194245e-01 -1.61957586e-01  5.39891139e-01]
 [ 1.33482098e+00  1.46184246e+00 -5.93723449e-01]
 [ 6.56671382e-01 -1.89079190e+00  9.25565081e-01]
 [ 1.02810579e+00 -9.03628214e-01  9.47871879e-01]]
[[ 0.54557525  2.23386824  0.02116786]
 [ 0.24338916 -0.10294189 -0.7408525 ]
 [-1.35556482  0.49975754 -0.03390486]
 [ 0.4136539  -0.69470825 -1.63612494]
 [ 2.54189417 -0.25753643 -0.7404461 ]]


In [132]:
np.add(data1,data2)

array([[ 0.54591935,  2.54434149,  0.40750045],
       [ 0.01919491, -0.26489948, -0.20096136],
       [-0.02074384,  1.9616    , -0.62762831],
       [ 1.07032528, -2.58550015, -0.71055986],
       [ 3.56999996, -1.16116464,  0.20742578]])

* 최대, 최소값 계산하기 : np.maximum(), np.minimum()