# Numpy

* numpy 모듈 선언
* 홈페이지 : https://numpy.org/

In [12]:
import numpy as np

In [13]:
np.__version__

'1.20.3'

## Array 정의 및 사용
* 시퀀스 데이터 ( 리스트, 튜플 등 ) 로부터 배열 생성
* https://numpy.org/doc/stable/reference/arrays.html

In [6]:
data1 = [1,2,3]
data1

[1, 2, 3]

In [7]:
data2 = [1,2,3,3.5,5]
data2

[1, 2, 3, 3.5, 5]

### 리스트 객체를 이용하여 array생성

In [8]:
arr1 = np.array(data1)
arr1

array([1, 2, 3])

#### array 크기 확인

In [10]:
arr1.shape

(3,)

#### 리스트를 직접 입력하여 array 생성

In [11]:
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [12]:
arr2.shape

(5,)

#### array의 자료형 확인

In [14]:
arr2.dtype     # c언어 기반이기 때문에 데이터 형식이 세분화되어있어서 int32가 뜸

dtype('int32')

In [15]:
arr3 = np.array([1,2,3,3.5,4])       # 실수가 더 큰 범위이므로 실수가 하나라도 
arr3                                 # 들어가면 소수점 처리해버림

array([1. , 2. , 3. , 3.5, 4. ])

In [16]:
arr3.dtype     # dtype = data type

dtype('float64')

In [17]:
arr3.shape

(5,)

In [22]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr4.shape

(3, 3)

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(1,5)

array([1, 2, 3, 4])

In [27]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [28]:
np.arange(12).reshape(3,4)      # reshape(행,열)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
b1 = np.arange(12).reshape(3,4)
b1.shape

(3, 4)

## 범위를 지정해 배열생성2 : linspace()함수
> 형식 : arr.obj = np.linspace(start, stop,[num=50])

In [30]:
# 1부터 10사이에 10개의 숫자를 넣는것
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
np.linspace(0,np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [33]:
np.linspace(1,10).shape

(50,)

## 특별한 형태의 배열생성
> np.zeros(), np.ones(), np.eye()

* 모든 요소가 0인 배열 생성 : np.zeros(shape, dtype=float)

In [34]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

* 모든 요소가 1인 배열 생성 : np.ones(shape, dtype=none)

In [35]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

* 대각요소가 1인 배열 생성 1 ; np.eye(n,m,k=K,dtype=none)

In [37]:
# 3행 3열의 대각요소가 1인 행렬. 타입이 '' 이면 기본값은 float
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
# 3행 4열의 대각요소가 1인 행렬 생성. 
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [39]:
# k는 열의 인덱스 위치를 의미함.
np.eye(3,4,k=1,dtype=int)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [40]:
np.eye(3,4,k=2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

* 대각요소가 1인 배열 생성 2 : np.identity(n,dtype=none)

In [41]:
# n*n 크기의 단위행렬 생성
np.identity(5)  # 5행 5열

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

* 초기화되지 않은 배열 생성 : np.empty(shape, dtype=float)

In [42]:
np.empty(4)

array([6.44448339e+247, 9.08367203e+223, 2.31647114e-152, 2.64685961e+180])

* 배열의 데이터 타입 변환

    * 문자열 배열을 숫자형 배열로 변환

In [44]:
np.array(['1.5','0.62','2','3.14','3.141592'])

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [46]:
# 문자열인 str_a1을 float형식으로 바꾸는 것
str_a1 = np.array(['1.5','0.62','2','3.14','3.141592'])
num_a1 = str_a1.astype(float)
num_a1

array([1.5     , 0.62    , 2.      , 3.14    , 3.141592])

In [47]:
str_a1.dtype

dtype('<U8')

In [48]:
num_a1.dtype

dtype('float64')

In [52]:
num_a2 = str_a1.astype(float).astype('float32')
num_a2

array([1.5     , 0.62    , 2.      , 3.14    , 3.141592], dtype=float32)

In [54]:
str_a2 = np.array(['1','3','5','7','9'])
num_a2 = str_a2.astype(int)
num_a2

array([1, 3, 5, 7, 9])

* 실수형 배열을 정수형 배열로 변환

In [16]:
num_f1 = np.array([10, 21, 0.549, 4.75, 5.98])
num_f1

array([10.   , 21.   ,  0.549,  4.75 ,  5.98 ])

In [56]:
num_i1 = num_f1.astype(int)
num_i1

array([10, 21,  0,  4,  5])

In [57]:
num_f1.dtype

dtype('float64')

In [60]:
num_i1.dtype

dtype('int32')

* 숫자형 배열을 문자열 배열로 변환

In [17]:
# 반올림하기
np.around(num_f1)

array([10., 21.,  1.,  5.,  6.])

In [62]:
num_f1.astype('U')

array(['10.0', '21.0', '0.549', '4.75', '5.98'], dtype='<U32')

In [64]:
num_f1.astype('S')

array([b'10.0', b'21.0', b'0.549', b'4.75', b'5.98'], dtype='|S32')

## 난수 배열 생성

### random.rand(), random.randint()

#### random.rand(d0,d1,...,dn)
* 0과1사이의 실수난수를 갖는 numpy배열 생성

In [65]:
np.random.rand()

0.04320281129230619

In [20]:
np.random.rand(3,3,4)

array([[[0.65755866, 0.15300237, 0.53043597, 0.12584811],
        [0.54012753, 0.51569213, 0.1514582 , 0.92918854],
        [0.09437641, 0.77587796, 0.09828656, 0.3586348 ]],

       [[0.2817147 , 0.42996793, 0.37273942, 0.3849081 ],
        [0.09935783, 0.79466575, 0.90434421, 0.6238419 ],
        [0.79659191, 0.38823539, 0.7843929 , 0.11214486]],

       [[0.69158787, 0.12614538, 0.13309486, 0.40452338],
        [0.6391867 , 0.50532374, 0.59220646, 0.2596032 ],
        [0.53009733, 0.55589761, 0.30172354, 0.02727078]]])

#### random.randint(low,high,size)
* [low,high]사이의 정수 난수를 갖는 numpy배열을 생성

In [68]:
np.random.randint(10)

1

In [69]:
np.random.randint(10,20)

18

In [72]:
np.random.randint(10,20,(3,5))

array([[12, 19, 18, 13, 17],
       [14, 10, 14, 11, 18],
       [17, 15, 11, 19, 10]])

## 기본 연산(합, 차, 곱, 나눗셈 등)
: 기본적으로 동일한 크기의 array간 연산 수행

In [74]:
arr1 = np.array([[1,3,4],[4,3,6]])
arr1

array([[1, 3, 4],
       [4, 3, 6]])

In [77]:
arr2 = np.arange(10,16).reshape(2,3)
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [78]:
print(arr1.shape, arr2.shape)

(2, 3) (2, 3)


### 배열의 합

In [80]:
arr1 + arr2

array([[11, 14, 16],
       [17, 17, 21]])

### 배열의 차

In [81]:
arr1 - arr2

array([[ -9,  -8,  -8],
       [ -9, -11,  -9]])

### 배열의 곱

In [82]:
arr1 * arr2

array([[10, 33, 48],
       [52, 42, 90]])

### 배열의 나눗셈

In [83]:
arr1 / arr2

array([[0.1       , 0.27272727, 0.33333333],
       [0.30769231, 0.21428571, 0.4       ]])

### 배열의 비교 연산

In [84]:
arr2 > 10

array([[False,  True,  True],
       [ True,  True,  True]])

## 배열의 Broadcasting
* 서로 크기가 다른 array들의 연산이 가능하도록 배열을 자동적으로 변환하여 연산 수행

In [85]:
arr1

array([[1, 3, 4],
       [4, 3, 6]])

In [88]:
arr3 = np.array([10,11,12])
arr3

array([10, 11, 12])

In [89]:
(arr1.shape, arr3.shape)

((2, 3), (3,))

In [90]:
arr1 + arr3

array([[11, 14, 16],
       [14, 14, 18]])

In [91]:
arr1 **2

array([[ 1,  9, 16],
       [16,  9, 36]], dtype=int32)